### ISSUE TITLE
panic on drive pull

### ISSUE THREAD

**Issue by zooks97** [prasmussen/gdrive#247]
go version go1.7.4 linux/amd64
kernel 4.8.15-300.fc25.x86_64

After running `drive pull`, the download starts fine but after 0.63% into an ~11gb download, i get this go panic:

```
panic: page 4 already freed

goroutine 1439 [running]:
panic(0x8b7320, 0xc4215a69a0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*freelist).free(0xc421161470, 0x93, 0x7f9d01e40000)
	/home/zooks/gopath/src/github.com/boltdb/bolt/freelist.go:121 +0x2c0
github.com/boltdb/bolt.(*node).spill(0xc42156ad90, 0xc4216faba0, 0xc4216faba0)
	/home/zooks/gopath/src/github.com/boltdb/bolt/node.go:363 +0x1dc
github.com/boltdb/bolt.(*node).spill(0xc42156aaf0, 0xc421161560, 0xc4201596c0)
	/home/zooks/gopath/src/github.com/boltdb/bolt/node.go:350 +0xb7
github.com/boltdb/bolt.(*Bucket).spill(0xc4215ac7c0, 0xc421161400, 0xc420159930)
	/home/zooks/gopath/src/github.com/boltdb/bolt/bucket.go:570 +0x43b
github.com/boltdb/bolt.(*Bucket).spill(0xc4203340f8, 0xf4e9895, 0xdface0)
	/home/zooks/gopath/src/github.com/boltdb/bolt/bucket.go:537 +0x93b
github.com/boltdb/bolt.(*Tx).Commit(0xc4203340e0, 0x0, 0x0)
	/home/zooks/gopath/src/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/boltdb/bolt.(*DB).Update(0xc4207e8000, 0xc420159b98, 0x0, 0x0)
	/home/zooks/gopath/src/github.com/boltdb/bolt/db.go:605 +0x10d
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc420145e40, 0xc4216bc600, 0x0, 0x0)
	/home/zooks/gopath/src/github.com/odeke-em/drive/config/config.go:279 +0x1a8
github.com/odeke-em/drive/src.(*Commands).createIndex(0xc420145ec0, 0xc4203c51e0, 0x9c68f0, 0xc420159c80)
	/home/zooks/gopath/src/github.com/odeke-em/drive/src/fetch.go:314 +0x138
github.com/odeke-em/drive/src.(*Commands).localAdd.func1(0xc420159d38, 0xc420489b80, 0xc420145ec0)
	/home/zooks/gopath/src/github.com/odeke-em/drive/src/pull.go:574 +0x63
github.com/odeke-em/drive/src.(*Commands).localAdd(0xc420145ec0, 0xc420489b80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/zooks/gopath/src/github.com/odeke-em/drive/src/pull.go:605 +0x241
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.localAdd)-fm(0xc420489b80, 0x0, 0x0, 0x0, 0x2, 0xc42005e400)
	/home/zooks/gopath/src/github.com/odeke-em/drive/src/misc.go:1066 +0x52
github.com/odeke-em/drive/src.(*Commands).playPullChanges.func2.1(0xc420489b80, 0x9c7710, 0xc42005e800)
	/home/zooks/gopath/src/github.com/odeke-em/drive/src/pull.go:477 +0x53
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0xc4202146c0, 0x41a0a5, 0x8b26a0, 0xc420a48f00)
	/home/zooks/gopath/src/github.com/odeke-em/drive/src/misc.go:120 +0xb1
github.com/odeke-em/drive/src.jobSt.Do(0xf, 0xc421010420, 0x60068f, 0x8b26a0, 0xc420a48f00, 0x0)
	/home/zooks/gopath/src/github.com/odeke-em/drive/src/misc.go:100 +0x27
github.com/odeke-em/drive/src.(*jobSt).Do(0xc420bae1e0, 0xc420b3d6e0, 0x0, 0x0, 0x0)
	<autogenerated>:6 +0x5b
github.com/odeke-em/semalim.Run.func4.1(0xc420b299d0, 0xc420a48de0, 0xc420b29a20, 0xc420b29a30, 0xdd0980, 0xc420bae1e0)
	/home/zooks/gopath/src/github.com/odeke-em/semalim/semalim.go:71 +0x56
created by github.com/odeke-em/semalim.Run.func4
	/home/zooks/gopath/src/github.com/odeke-em/semalim/semalim.go:76 +0x141
```

**Comment by animesh** [comment]
Having the same issue, but while push-ing changes...

**Comment by anpar** [comment]
Same for me, only while pulling.
