### ISSUE TITLE
runtime: failed to create new OS thread (have 49 already; errno=12)

### ISSUE THREAD

**Issue by vypinac** [prasmussen/gdrive#595]
Hello,

we would like to use gdrive to backup files from shared webhosting.
There is enforced OS limit for 50 processes and probably therefore the upload files.
Would it be possible to add an option to limit the process/thread usage of gdrive please?

Thanks.

sconnor@darpanet [~]# /home/sconnor/bin/gdrive upload --parent gid --recursive /home/sconnor/public_html
Creating directory public_html
Creating directory storage
Creating directory framework
Creating directory views
Uploading /home/sconnor/public_html/storage/framework/classes.php
Uploading /home/sconnor/public_html/storage/framework/packages.php
Creating directory cache
Creating directory 17
Creating directory d1
Uploading /home/sconnor/public_html/storage/framework/cache/17/d1/17d1c14abb090e2e9d5ead54f8f6ba691228f573
*cut*
Uploading /home/sconnor/public_html/storage/framework/cache/4a/29/4a29b289567e2d03ab408c540c7640d948941f80
runtime: failed to create new OS thread (have 49 already; errno=12)
fatal error: newosproc

runtime stack:
runtime.throw(0x8302473, 0x9)
/usr/local/go/src/runtime/panic.go:608 +0x6a
runtime.newosproc(0xa4db4a0)
/usr/local/go/src/runtime/os_linux.go:166 +0x195
runtime.newm1(0xa4db4a0)
/usr/local/go/src/runtime/proc.go:1940 +0xdb
runtime.newm(0x83186d8, 0x0)
/usr/local/go/src/runtime/proc.go:1919 +0x88
runtime.startTheWorldWithSema(0x1, 0xb89f0802, 0xa1e668c)
/usr/local/go/src/runtime/proc.go:1209 +0x1be
runtime.gcMarkTermination.func3()
/usr/local/go/src/runtime/mgc.go:1644 +0x1e
runtime.systemstack(0xa4fd180)
/usr/local/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1229

goroutine 18 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_386.s:357 fp=0xa1e65cc sp=0xa1e65c8 pc=0x8093cd0
runtime.gcMarkTermination(0xcc208fce, 0x3fed57a0)
/usr/local/go/src/runtime/mgc.go:1644 +0x6e3 fp=0xa1e677c sp=0xa1e65cc pc=0x805e533
runtime.gcMarkDone()
/usr/local/go/src/runtime/mgc.go:1510 +0x213 fp=0xa1e679c sp=0xa1e677c pc=0x805de03
runtime.gcBgMarkWorker(0xa023300)
/usr/local/go/src/runtime/mgc.go:1909 +0x2a1 fp=0xa1e67e8 sp=0xa1e679c pc=0x805f011
runtime.goexit()
/usr/local/go/src/runtime/asm_386.s:1324 +0x1 fp=0xa1e67ec sp=0xa1e67e8 pc=0x8095521
created by runtime.gcBgMarkStartWorkers
/usr/local/go/src/runtime/mgc.go:1720 +0x61

goroutine 1 [select]:
github.com/prasmussen/gdrive/vendor/golang.org/x/net/context/ctxhttp.Do(0xe74c5318, 0xa57a2c0, 0xa1327a0, 0xa3a8100, 0x18, 0xa53401a, 0x16)
/go/src/github.com/prasmussen/gdrive/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:55 +0x139
github.com/prasmussen/gdrive/vendor/google.golang.org/api/drive/v3.(*FilesCreateCall).doRequest(0xa154380, 0x83011c7, 0x4, 0x0, 0x0, 0x0)
/go/src/github.com/prasmussen/gdrive/vendor/google.golang.org/api/drive/v3/drive-gen.go:3070 +0x41f
github.com/prasmussen/gdrive/vendor/google.golang.org/api/drive/v3.(*FilesCreateCall).Do(0xa154380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/prasmussen/gdrive/vendor/google.golang.org/api/drive/v3/drive-gen.go:3084 +0x76
github.com/prasmussen/gdrive/drive.(*Drive).uploadFile(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa378070, 0x61, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:187 +0x436
github.com/prasmussen/gdrive/drive.(*Drive).uploadRecursive(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa378070, 0x61, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:95 +0x10b
github.com/prasmussen/gdrive/drive.(*Drive).uploadDirectory(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa01a480, 0x38, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:137 +0x494
github.com/prasmussen/gdrive/drive.(*Drive).uploadRecursive(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa01a480, 0x38, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:93 +0x170
github.com/prasmussen/gdrive/drive.(*Drive).uploadDirectory(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa34e080, 0x35, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:137 +0x494
github.com/prasmussen/gdrive/drive.(*Drive).uploadRecursive(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa34e080, 0x35, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:93 +0x170
github.com/prasmussen/gdrive/drive.(*Drive).uploadDirectory(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa01b240, 0x32, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:137 +0x494
github.com/prasmussen/gdrive/drive.(*Drive).uploadRecursive(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa01b240, 0x32, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:93 +0x170
github.com/prasmussen/gdrive/drive.(*Drive).uploadDirectory(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa374090, 0x2c, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:137 +0x494
github.com/prasmussen/gdrive/drive.(*Drive).uploadRecursive(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa374090, 0x2c, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:93 +0x170
github.com/prasmussen/gdrive/drive.(*Drive).uploadDirectory(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa3d80c0, 0x22, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:137 +0x494
github.com/prasmussen/gdrive/drive.(*Drive).uploadRecursive(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xa3d80c0, 0x22, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:93 +0x170
github.com/prasmussen/gdrive/drive.(*Drive).uploadDirectory(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xffb36644, 0x1a, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:137 +0x494
github.com/prasmussen/gdrive/drive.(*Drive).uploadRecursive(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xffb36644, 0x1a, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:93 +0x170
github.com/prasmussen/gdrive/drive.(*Drive).Upload(0xa00ed78, 0x8377430, 0xa00e0f8, 0x8377430, 0xa00e100, 0xffb36644, 0x1a, 0x0, 0x0, 0x0, ...)
/go/src/github.com/prasmussen/gdrive/drive/upload.go:47 +0x721
main.uploadHandler(0xa132420, 0xa020280, 0x1d, 0x1d)
/go/src/github.com/prasmussen/gdrive/handlers_drive.go:117 +0x51a
github.com/prasmussen/gdrive/cli.Handle(0xa010038, 0x5, 0x5, 0xa06f180)
/go/src/github.com/prasmussen/gdrive/cli/handler.go:104 +0xa4
main.main()
/go/src/github.com/prasmussen/gdrive/gdrive.go:856 +0x8e61

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0xe74c4f40, 0x72, 0x80cb0d9)
/usr/local/go/src/runtime/netpoll.go:173 +0x4b
internal/poll.(*pollDesc).wait(0xa1e0064, 0x72, 0xffffff00, 0x8377e10, 0x85110dc)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x7d
internal/poll.(*pollDesc).waitRead(0xa1e0064, 0xa216000, 0x2000, 0x2000)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x32
internal/poll.(*FD).Read(0xa1e0050, 0xa216000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x147
net.(*netFD).Read(0xa1e0050, 0xa216000, 0x2000, 0x2000, 0x804eb2f, 0x8540ec0, 0x82c01e0)
/usr/local/go/src/net/fd_unix.go:202 +0x3f
net.(*conn).Read(0xa1c8088, 0xa216000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:177 +0x56
crypto/tls.(*block).readFromUntil(0xa1bc660, 0x83771d0, 0xa1c8088, 0x5, 0xa1c8088, 0x8075aff)
/usr/local/go/src/crypto/tls/conn.go:492 +0x6b
crypto/tls.(*Conn).readRecord(0xa20a000, 0x8318717, 0xa20a0a4, 0xa030648)
/usr/local/go/src/crypto/tls/conn.go:593 +0xb5
crypto/tls.(*Conn).Read(0xa20a000, 0xa4c0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:1145 +0xd7
bufio.(*Reader).Read(0xa1e4570, 0xa020220, 0x9, 0x9, 0x0, 0x1, 0x806d60e)
/usr/local/go/src/bufio/bufio.go:216 +0x1cb
io.ReadAtLeast(0x8376d30, 0xa1e4570, 0xa020220, 0x9, 0x9, 0x9, 0x11, 0x1000, 0x11)
/usr/local/go/src/io/io.go:310 +0x78
io.ReadFull(0x8376d30, 0xa1e4570, 0xa020220, 0x9, 0x9, 0x81ebbbe, 0xa20a000, 0xa14d000)
/usr/local/go/src/io/io.go:329 +0x45
net/http.http2readFrameHeader(0xa020220, 0x9, 0x9, 0x8376d30, 0xa1e4570, 0x0, 0x0, 0x0, 0xa03063c, 0xa030600)
/usr/local/go/src/net/http/h2_bundle.go:1545 +0x66
net/http.(*http2Framer).ReadFrame(0xa020200, 0xa3ac660, 0x0, 0x0, 0x0)
/usr/local/go/src/net/http/h2_bundle.go:1803 +0x7b
net/http.(*http2clientConnReadLoop).run(0xa0adfdc, 0x83184c8, 0xa0537dc)
/usr/local/go/src/net/http/h2_bundle.go:8293 +0x6d
net/http.(*http2ClientConn).readLoop(0xa0a25a0)
/usr/local/go/src/net/http/h2_bundle.go:8221 +0x65
created by net/http.(*http2Transport).newClientConn
/usr/local/go/src/net/http/h2_bundle.go:7294 +0x574

goroutine 299 [select]:
net/http.(*http2ClientConn).roundTrip(0xa0a25a0, 0xa3a8180, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/net/http/h2_bundle.go:7695 +0x663
net/http.(*http2Transport).RoundTripOpt(0xa0114a0, 0xa3a8180, 0x8056300, 0x830142f, 0xa534000, 0x5)
/usr/local/go/src/net/http/h2_bundle.go:7067 +0x114
net/http.(*http2Transport).RoundTrip(0xa0114a0, 0xa3a8180, 0x82f2200, 0x0, 0xa57a440)
/usr/local/go/src/net/http/h2_bundle.go:7029 +0x2e
net/http.http2noDialH2RoundTripper.RoundTrip(0xa0114a0, 0xa3a8180, 0xa534000, 0x5, 0xa097cf8)
/usr/local/go/src/net/http/h2_bundle.go:1019 +0x2d
net/http.(*Transport).roundTrip(0x853f720, 0xa3a8180, 0xa3a8100, 0xa09a258, 0xa132790)
/usr/local/go/src/net/http/transport.go:415 +0xa4d
net/http.(*Transport).RoundTrip(0x853f720, 0xa3a8180, 0xa3a8180, 0x0, 0x29)
/usr/local/go/src/net/http/roundtrip.go:17 +0x29
github.com/prasmussen/gdrive/vendor/golang.org/x/oauth2.(*Transport).RoundTrip(0xa132780, 0xa3a8100, 0xa132780, 0x0, 0x0)
/go/src/github.com/prasmussen/gdrive/vendor/golang.org/x/oauth2/transport.go:48 +0xa8
net/http.send(0xa3a8100, 0x8376fb0, 0xa132780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80955e3, 0xa554e50, ...)
/usr/local/go/src/net/http/client.go:250 +0x14d
net/http.(*Client).send(0xa1327a0, 0xa3a8100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0xa0a25cc, 0x0, ...)
/usr/local/go/src/net/http/client.go:174 +0xaa
net/http.(*Client).do(0xa1327a0, 0xa3a8100, 0x0, 0x0, 0x0)
/usr/local/go/src/net/http/client.go:641 +0x257
net/http.(*Client).Do(0xa1327a0, 0xa3a8100, 0xa0707c0, 0xb5abfe4, 0xa00eed8)
/usr/local/go/src/net/http/client.go:509 +0x29
github.com/prasmussen/gdrive/vendor/golang.org/x/net/context/ctxhttp.Do.func1(0xa1327a0, 0xa3a8100, 0x8318360, 0xa154480)
/go/src/github.com/prasmussen/gdrive/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:48 +0x2d
created by github.com/prasmussen/gdrive/vendor/golang.org/x/net/context/ctxhttp.Do
/go/src/github.com/prasmussen/gdrive/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:47 +0xac
sconnor@darpanet [~]#

**Comment by DarthJahus** [comment]
Getting the same error, here. Thread limited, for sure. But isn't there a way to use less threads?
